### ISSUE TITLE
Add category for security

### ISSUE THREAD

**Issue by jakebolam** [kentcdodds/all-contributors#106]
Possible emoji: 🛡️

See CLI PR: https://github.com/jfmengels/all-contributors-cli/pull/126

**Comment by kentcdodds** [comment]
I'm in favor I think. Could you make a PR?

**Comment by jakebolam** [comment]
@kentcdodds put a PR up here, will do one on the CLI too https://github.com/kentcdodds/all-contributors/pull/107

**Comment by kentcdodds** [comment]
Merged 💯
