### ISSUE TITLE
Reformat Contributors

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/all-contributors#13]
It's crazy long. I'm thinking of doing something like [this](https://github.com/mgechev/angular2-seed#contributors):

<img width="899" alt="screen shot 2016-03-01 at 8 53 34 am" src="https://cloud.githubusercontent.com/assets/1500684/13432494/18edee04-df8b-11e5-9ec5-1c94de5c1dd8.png">

Will submit a PR soon.

**Comment by kentcdodds** [comment]
Whoops... Didn't mean to close this...

**Comment by Jameskmonger** [comment]
Can this be closed now @kentcdodds ?

**Comment by kentcdodds** [comment]
Ah, yes, it can. Thanks!
