### ISSUE TITLE
Alt category text when user hovers over Contribution Category emoji icon

### ISSUE THREAD

**Issue by chrissimpkins** [kentcdodds/all-contributors#16]
Maybe a built in key for the emoji by including alt text that specifies the category that it represents?

**Comment by Jameskmonger** [comment]
Yeah I'd like to see this too. It'd make it easier for projects to adopt because they wouldn't (necessarily) have to have the emoji key on their own repo.

**Comment by Jameskmonger** [comment]
(sorry for closing! clicked the wrong button by accident. reopened)

**Comment by chrissimpkins** [comment]
These emoji icons are handled as text.  Is there a way to add an alt tag to them in Markdown?

**Comment by kentcdodds** [comment]
Huh, that's a good point... I don't think that's possible. Also `alt` is actually not an attribute of an `<a>` tag anyway, so it'd have to be an `<img>`. I'm not sure I want to do that though :-/

**Comment by jfmengels** [comment]
Unless somebody finds a solution, I'm closing it. (Please re-open if you don't agree)

**Comment by chrissimpkins** [comment]
agree

**Comment by kevinjalbert** [comment]
After some playing around a bit with GitHub's markdown, I came up with the following:

`[:eyes:](#eyes-kevinjalbert "Reviewed Pull Requests")`
[:eyes:](#eyes-kevinjalbert "Reviewed Pull Requests")

This way we can attach an alt text (really the `title` attribute) on a link, where the value of the link is the the emoji. As for the actual `href`, using `#xxxxx` lets you not mess with the navigation assuming you have unique keys. In my example, I'm simply using the emoji's key and github user name (i.e., <emoji-username>).

Any idea if this is something that would work?

**Comment by kentcdodds** [comment]
That appears to look (couldn't get a screenshot, but it works :smile:). Though I'm thinking that because we now have [the CLI](https://github.com/jfmengels/all-contributors-cli) we don't really need to worry about using strictly Markdown to do this. We can just add it to the template. Would you be interested in [making a pull request](http://makeapullrequest.com/) to that project?

**Comment by kevinjalbert** [comment]
I think there is still value in having markdown as the main use-case (just from a README mostly being in markdown).

I can take a stab at the PR on the CLI maybe this weekend.

**Comment by kevinjalbert** [comment]
@kentcdodds https://github.com/jfmengels/all-contributors-cli/pull/42 ;) Let me know if there is anymore to be done or changed in the PR (on the PR)
