### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by chrissimpkins** [kentcdodds/all-contributors#21]
Everyone loves a badge :)  Link it to the contributors list?

![All Contributors](https://img.shields.io/badge/Contributors-All-blue.svg?style=flat)

![All Contributors](https://img.shields.io/badge/Contributors-All-green.svg?style=flat)

![All Contributors](https://img.shields.io/badge/Contributors-All-red.svg?style=flat)

![All Contributors](https://img.shields.io/badge/Contributors-All-orange.svg?style=flat)

![All Contributors](https://img.shields.io/badge/Contributors-All-yellow.svg?style=flat)

**Comment by kentcdodds** [comment]
I've been thinking about that too. Would love ideas from other contributors as well!

I personally like the flat-square style, and I'd prefer to be able to read it like it's in a sentence, so how about these?


![All Contributors](https://img.shields.io/badge/All-Contributors-blue.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/All-Contributors-green.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/All-Contributors-red.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/All-Contributors-orange.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/All-Contributors-yellow.svg?style=flat-square)

**Comment by kentcdodds** [comment]
Or how about:

![All Contributors](https://img.shields.io/badge/Contributions-Welcome-blue.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/Contributions-Welcome-green.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/Contributions-Welcome-red.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/Contributions-Welcome-orange.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/Contributions-Welcome-yellow.svg?style=flat-square)

**Comment by kentcdodds** [comment]
Or maybe lower case...

![All Contributors](https://img.shields.io/badge/contributons-welcome-blue.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/contributons-welcome-green.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/contributons-welcome-red.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/contributons-welcome-orange.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/contributons-welcome-yellow.svg?style=flat-square)


![All Contributors](https://img.shields.io/badge/all-contributors-blue.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/all-contributors-green.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/all-contributors-red.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/all-contributors-orange.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/all-contributors-yellow.svg?style=flat-square)

**Comment by kentcdodds** [comment]
And of course, we'd recommend that it link to [the spec](https://github.com/kentcdodds/all-contributors) right?

**Comment by Jameskmonger** [comment]
I prefer `all contributors` to `contributors welcome`, the `contributors welcome` badge to me doesn't say much other than `accepting pull requests`.

**Comment by kentcdodds** [comment]
> `contributors welcome` badge to me doesn't say much other than `accepting pull requests`

Agreed.

**Comment by kentcdodds** [comment]
I'm leaning toward: ![All Contributors](https://img.shields.io/badge/all-contributors-orange.svg?style=flat-square)

**Comment by chrissimpkins** [comment]
I like `contributors all` or `all contributors` and don't have a strong opinion one way or the other about the case.

As for the link, it really depends upon whether you want to emphasize the project's contributors or the specification.  I tend to favor that the badge leads to the contributor list for the project rather than the specification.  Including this at the top of your README file would be a way to emphasize the collaborative nature of the project and provide an accessible link to the contributor list wherever that may live in the project repository.

My initial thought with the `Contributors All` is that this could be used as a generic badge for those who don't care to keep up with the number but want to indicate that they acknowledge the contributions of all contributors as defined by the spec.  Users could modify the badge with actual contributor numbers if they choose to maintain it for their repository.  This would allow the All Contributors spec definition to "override" the contributor numbers associated with the repository as defined by GitHub commits.

![All Contributors](https://img.shields.io/badge/all_contributors-35-orange.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/All_Contributors-35-orange.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/35-all_contributors-orange.svg?style=flat-square)

![All Contributors](https://img.shields.io/badge/35-All_Contributors-orange.svg?style=flat-square)

Just my 2 cents.  This should be your decision Kent.  I introduced it because I like to look at badges :eyes: :+1:

**Comment by kentcdodds** [comment]
I agree this should link to the list. Also the number would be awesome. I'll bet @jfmengels's tool could keep that number up to date :+1:

**Comment by jfmengels** [comment]
Should not be too much of a problem :+1:

**Comment by chrissimpkins** [comment]
Did we settle on a design?

**Comment by kentcdodds** [comment]
I like the first one in that last comment

**Comment by chrissimpkins** [comment]
#31
