### ISSUE TITLE
Mobile alignment

### ISSUE THREAD

**Issue by Jameskmonger** [kentcdodds/all-contributors#29]
Just looked at the readme on my mobile (Nexus 5) and the tables look pretty badly aligned.

![tables](http://i.imgur.com/3awZobX.png)

Not sure if this is something we can fix, though?

**Comment by kentcdodds** [comment]
Yeah :-( Too bad there's no way to do responsive design in markdown.........

**Comment by kentcdodds** [comment]
I'm going to vote: `wont fix`

**Comment by Jameskmonger** [comment]
Sure, I'm happy with that vote @kentcdodds.

**Comment by Hemanthkumar2112** [comment]
og
