### ISSUE TITLE
Have an emoji for issues/feature requests/discussion

### ISSUE THREAD

**Issue by jfmengels** [kentcdodds/all-contributors#30]
We should have an emoji and a name for creating feature requests, and/or simply discussing/bikeshedding in issues and PRs.

Kinda stuck on finding a name for this (or rather, a `represents` value as is written in the emoji table), and I'm not too familiar with emojis either.

Any thoughts on this? :)

**Comment by kentcdodds** [comment]
I'm a fan of the idea. How about 🌟?

**Comment by jfmengels** [comment]
:+1:

**Comment by jfmengels** [comment]
🌟 LGTM.
I'm tempted to call this  ̀discussion`.

**Comment by kentcdodds** [comment]
I'd be worried that would be too loose. Bikeshedding is not always constructive. Only people with real-world use cases that are within the scope of the project should be considered. I think something that describes the concept "Accepted Feature Requests" would be better... :thought_balloon:

**Comment by jfmengels** [comment]
Agreed, but I think it would be nice to have one for people that discuss a lot in GH issues (bikeshedding or more useful comments).

**Comment by ligthyear** [comment]
If you call it discussions, I'd vote for the speech bubble: 💬

**Comment by kentcdodds** [comment]
I'm a fan of that.

**Comment by patcon** [comment]
Is this good to close now?

**Comment by kentcdodds** [comment]
Yep, thanks!
