### ISSUE TITLE
Add Emoji for Infrastructure work

### ISSUE THREAD

**Issue by ligthyear** [kentcdodds/all-contributors#33]
First off: love the idea/project. I am currently implementing it for [a project of mine], and even though it is with 4 contributors still quite small, already found myself with a few rather odd places with the emoji. I will post them as separate issue so we can discuss each suggestion I have.

This one is about "infrastructure work" someone might contributed. In my case this means setting up build-services (like travis), hosting, maintain servers etc. I suggest to use the "power plug" emoji: 🔌

(One could argue that this could be merged with "tools" but then we should adapt the language for that one to explicitly include that sort of thing)

**Comment by ligthyear** [comment]
Sorry, didn't realise that was the same emoji as for plugin contributions. I'm not really sure which other emoji to pick though. Suggestions welcome!

**Comment by ligthyear** [comment]
How about factory: 🏭, metro 🚇 or postal horne📯 as generalised symbols for infrastructure?

**Comment by Jameskmonger** [comment]
I like :metro:!

**Comment by chrissimpkins** [comment]
@ligthyear @Jameskmonger :+1:

**Comment by kentcdodds** [comment]
I'm also good with 🚇 :+1:

Feel free to [makeapullrequest.com](http://makeapullrequest.com) and don't forget to add yourself to the list of contributors in that PR :-)
