### ISSUE TITLE
Question-Mark is ... awkward

### ISSUE THREAD

**Issue by ligthyear** [kentcdodds/all-contributors#35]
The big red (or black) question mark looks like something failed to load or the position of that person is questionable/unknown. Making it a very awkward emoji to use. Once you read the spec it feels like it makes sense, but when you see it in a Readme, even after that, it is just not very positive. Can't we at least use the "answered" version of that emoji: ⁉️ – or is that just no strong enough in most fonts?

**Comment by ben-eb** [comment]
Perhaps we could use a lightbulb 💡 instead?

**Comment by ben-eb** [comment]
Realised we use lightbulb already for 'examples'. How about 🙋?

**Comment by ligthyear** [comment]
I like the raise-the-hand – generally fan of the human-emoticons ;) . Still feels more like the quenstion-answering rather than the helping person, no? How about information-desk-person: 💁 ?

**Comment by kentcdodds** [comment]
I'm good with 💁

**Comment by kentcdodds** [comment]
Feel free to [makeapullrequest.com](http://makeapullrequest.com) :-)

**Comment by ligthyear** [comment]
@kentcdodds is it ok if combine this and the PR for #33 into one?

**Comment by kentcdodds** [comment]
Generally want to avoid that just in case someone's good with #33 and not with #30. So why don't you make one for each and then an additional one to add yourself to the contributors table :)
