### ISSUE TITLE
List projects that adopt all-contributors

### ISSUE THREAD

**Issue by diegohaz** [kentcdodds/all-contributors#43]
It would be nice to have a list of those projects so people can find them more easily.

**Comment by kentcdodds** [comment]
That'd be great! Should be reasonably easy to find as most projects will probably be using @jfmengels's tool (and will hence have an `.all-contributorsrc` file). So you can find them with a file search on GitHub: https://github.com/search?utf8=%E2%9C%93&q=.all-contributorsrc+in%3Apath&type=Code&ref=searchresults

I'll create an initial file with a few projects and leave it open to anyone else to add more projects. Don't forget to follow [the contributing guidelines](https://github.com/kentcdodds/all-contributors/blob/master/CONTRIBUTING.md) :)

**Comment by maltfield** [comment]
@kentcdodds @jfmengels the search query is broken

**Comment by Drakogangcom** [comment]
> **``**
https://youtu.be/ciiodtemqw8
🎥 REMBLE X DRAKEO THE RULER - “Ruth’s Chris Freestyle” (OFFICIAL MUSIC VIDEO)
