### ISSUE TITLE
When a contributor changes his username, it breaks the table layout

### ISSUE THREAD

**Issue by diegohaz** [kentcdodds/all-contributors#52]
In the case below (from [ARc](https://github.com/diegohaz/arc)), Abhishek changed his username. So link and picture doesn't exist and broke the table layout.

![image](https://cloud.githubusercontent.com/assets/3068563/23074276/7f30ee46-f51f-11e6-8947-4bd68044699a.png)

**Comment by kentcdodds** [comment]
Are you using [the CLI](https://github.com/jfmengels/all-contributors-cli)? This shouldn't happen with the CLI.

**Comment by diegohaz** [comment]
I can't use the CLI directly on the repository (automated) because this is a boilerplate. Is there something we can do to don't break the layout when it happens?

**Comment by kentcdodds** [comment]
Hmmm... I don't think the CLI had this problem so you could probably compare your table to the one the CLI creates. This repo uses the CLI so you could check this one.

**Comment by diegohaz** [comment]
What happened was Abhishek Shende changed his GitHub username from abhishekisnot to osdevisnot, which breaks the link https://github.com/abhishekisnot and his picture. That giant octocat is the default GitHub picture, but it doesn't take the `s=100` querystring, breaking the table layout.

Of course, this is a very edge case and the obvious solution is to update his data on the `README`/`.all-contributorsrc`, but on some projects it could take awhile until someone notice.

**Comment by diegohaz** [comment]
Not directly related to this issue, but...

The problem of using the CLI on a boilerplate is the `.all-contributorsrc` file. It doesn't make much sense for boilerplate users to create their projects with `all-contributors`. It would just create another step for them to setup a clean project (that's why I also try to avoid adding other repository specific stuff like `.github/` etc.).

Because of that I choose to keep all-contributors only on README.md and use the Atom plugin to generate the table.

**Comment by kentcdodds** [comment]
Gotcha. I'd recommend adding a script called "setup" that removes all the extra files. Or even better, you could change it to a Yeoman generator 😀

**Comment by diegohaz** [comment]
Yeah, thank you for the suggestions. :)

I'm just posting this issue here because we might find an easy solution for this. For example, using html instead of markdown should prevent it to break the layout until someone updates the contributor info:
```html
<img src="https://avatars.githubusercontent.com/abhishekisnot?s=100" width="100" alt="Abhishek Shende" />
```

**Comment by diegohaz** [comment]
Created a PR there. Thank you for your support and sorry about the mess, @kentcdodds.

**Comment by kentcdodds** [comment]
No worries!
