### ISSUE TITLE
Emoji title

### ISSUE THREAD

**Issue by charlike** [kentcdodds/all-contributors#59]
I think it would be better when hover on some emoji on generated list of all contributors to show what that emoji means. Because currently it shows the code for emoji (for example, `:eyes:`), which kinda force you to navigate to the space (almost always, until you learn all of them ;d) to see what it means.

**Comment by kentcdodds** [comment]
Agreed. The CLI's responsible for this. Would you like to make a PR there? https://github.com/jfmengels/all-contributors-cli

**Comment by tunnckoCore** [comment]
Cool! I will in monday. :)

**Comment by revelt** [comment]
I came here exactly for the same reason, the title is not set correctly currently, current-labels don't make sense and kindof spoils the whole concept..

![screen shot 2017-10-02 at 00 43 34](https://user-images.githubusercontent.com/8344688/31060391-e5f338e4-a70a-11e7-94cb-cae48d27e4c9.png)

I would implement this on my libraries but I want emoji titles ironed out first.

**Comment by charlike** [comment]
@revelt same here, i gonna include it in my future readmes too.

Sorry, i seen my previous comment and forgot about that my promise. I can hopefully do it soon :)

**Comment by revelt** [comment]
@charlike haha it happened to me too, I think it's some sort of Murphy's law - it's enough to promise anything, no matter how simple, suddenly errands will swoop in and you won't get it done. Off the record, I think you would be featured on some of my libs if I implemented this :) I know I definitely consume your libs, just don't remember if contributed anything. I remember I contributed bugs on others where you participated..

It's an awesome concept to mention everybody.

**Comment by kentcdodds** [comment]
I think this is actually resolved... You can see in [the downshift repo](https://github.com/paypal/downshift) :)

**Comment by revelt** [comment]
Hi Kent! Sorry, I checked, it does not appear:

![screen shot 2017-10-02 at 07 44 08](https://user-images.githubusercontent.com/8344688/31066540-99197ff2-a745-11e7-858c-1203791818d5.png)

I would expect to see not `:metro:` but `infrastructure`. Does it make sense?

**Comment by charlike** [comment]
> haha it happened to me too, I think it's some sort of Murphy's law - it's enough to promise anything, no matter how simple, suddenly errands will swoop in and you won't get it done.

yea, absolutely.

> Off the record, I think you would be featured on some of my libs if I implemented this :) I know I definitely consume your libs, 

Nice, thanks! :)

> I think this is actually resolved... You can see in the downshift repo :)

Mmmnope. It's not. 

edit: haha, @revelt posted before me

**Comment by revelt** [comment]
hehe :)

**Comment by kentcdodds** [comment]
Hmmm... It's working for me: 

![working](https://user-images.githubusercontent.com/1500684/31079523-27a7ab34-a743-11e7-89fb-5dca0b2f680b.png)

@charlike, sounds cool. `kcd-scripts` is also capable of config and also uses itself to build itself :wink:

Any idea why this seems to be working for me and not you folks? Here's what the DOM looks like on that particular emoji for me:

```html
<a href="#infra-kentcdodds" title="Infrastructure (Hosting, Build-Tools, etc)"><g-emoji alias="metro" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f687.png" ios-version="6.0">🚇</g-emoji></a>
```

**Comment by revelt** [comment]
Maybe it's different software combo.. 
I'm using latest Chrome on Mac OS.

@kentcdodds From your cursor I see it's a mac. What browser are you on?

**Comment by revelt** [comment]
Just checked, Mac OS, Safari 11 does not show any title balloons at all.
It also doesn't show any title popups on Firefox 55 (which is updating currently).

**Comment by kentcdodds** [comment]
I'm on latest Chrome on Mac OS... What's the DOM look like for you? I think the most likely thing is that we're seeing a different DOM structure due to an A/B test from GitHub or something....

**Comment by revelt** [comment]
@kentcdodds Here's a whole `th` tag, your card from this very library's readme front page.

```html
<th align="center"><a href="https://kentcdodds.com"><img src="https://avatars.githubusercontent.com/u/1500684?v=3" width="100px;" style="max-width:100%;"><br><sub>Kent C. Dodds</sub></a><br><g-emoji alias="tipping_hand_woman" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f481.png" ios-version="6.0" title=":tipping_hand_woman:">💁</g-emoji> <a href="https://github.com/kentcdodds/all-contributors/commits?author=kentcdodds"><g-emoji alias="book" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f4d6.png" ios-version="6.0" title=":book:">📖</g-emoji></a> <g-emoji alias="eyes" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f440.png" ios-version="6.0" title=":eyes:">👀</g-emoji> <g-emoji alias="loudspeaker" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f4e2.png" ios-version="6.0" title=":loudspeaker:">📢</g-emoji></th>
```

**Comment by kentcdodds** [comment]
Yeah, looks like GitHub is showing you something different from what it's showing me. So there's not much we can do about that I'm afraid :-(

**Comment by charlike** [comment]
Hm, yea, it's interesting, because it actually adds the `title` attribute to the anchor, but it seems that the emoji (g-emoji tag) and the img tag (which is fallbacked) are on top of the anchor link, so when you hover you it can't show the anchor's title attribute but the emoji's one.

My case is strange too. I'm on latest Chrome 61+ and ArchLinux, but it seems that it uses/fallbacks ti img instead of emojis.

```html
<a
  href="https://github.com/paypal/downshift/commits?author=kentcdodds"
  title="Code">
<g-emoji
  alias="computer"
  fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f4bb.png"
  ios-version="6.0"
  title=":computer:">
<img
  class="emoji"
  alt=":computer:"
  height="20"
  width="20"
  src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f4bb.png">
</g-emoji></a>
```

**Comment by charlike** [comment]
Don't know but it is something from the browsers i believe. Because i never seen the `semantic-release` 's badge left-side emojis, but on the phone i seeing them.

![2017-10-02-19 01 56_227x97_scrot](https://user-images.githubusercontent.com/5038030/31087052-5640c866-a7a4-11e7-91a5-6e75c2e201d3.png)
 _(huh, one more lesson today - the three adblockers that i have seems to block the uploading image on comments functionality ;d;d;d)_

**Comment by revelt** [comment]
That's an interesting case. My next thought is to try to simplify the markup, maybe the current situation within markdown/html is too fancy?

**Comment by charlike** [comment]
It's github job.. so we can't do another thing. But the great thing is that we can play here inside the comments directly, instead of waste time in PRs and commits :D :D

**Comment by revelt** [comment]
:DD

**Comment by charlike** [comment]
PROOOOOOBABLY an Chrome/Firefox extension? :D Or addition to the Refined Github too ;d

Then we just need to select all `g-emoji[title]` and replace their title attributes trimming the `:` ;d

**Comment by revelt** [comment]
I turned off "Hide files on GitHub" and "Redefined GitHub" extensions on mine, no difference..

**Comment by charlike** [comment]
No no, i meant addition to them to be PR-ed. :P

**Comment by charlike** [comment]
Btw, see https://github.com/kentcdodds/all-contributors/issues/59#rofling-title-works - it WORKS! :D

**Comment by revelt** [comment]
I'm looking at raw readme, it's all in markdown. What if we put raw HTML?

**Comment by charlike** [comment]
Yea, i was thinking that too but forgot to add it to the bullets.

**Comment by charlike** [comment]
The above thing that is the rofling emoji, may work because github has two markdown solutions. Don't know how to explain it, but i have seen some things that work in a READMEs and other md files, but not in the comments. Some micro things.

**Comment by charlike** [comment]
GODDAMMN :rofl: For sum freaking reason this did the trick

putting directly in markdown, generates same thign, but does not add the `title` attribute to the `g-emoji` tag, which is the main reason what we see ;d

```md
<a
  href="https://github.com/paypal/downshift/commits?author=kentcdodds"
  title="Code">
[:metro:](#infra "metrox")</a>
```

**Comment by revelt** [comment]
yeahhh!!!! good job!!!

**Comment by charlike** [comment]
I'M THE MACHINEEEE :D I'll PR to see if it really works :smile:

**Comment by charlike** [comment]
Okey, it not works. This is one of these cases that i'm talking about. When is in the comments - it works, when is in the preview while writing a comment - it works, when you are previewing and editing some file through the github ui - it works. But when it is rendered on the readme (and other md files) this trick does not work.

So there really is no way to tweak it, except in extension. Totally new or just suggest it to the Refined Github it is 2 lines of code.

```js
let emojis = document.querySelectorAll('table td[align="center"] a[title] g-emoji')
for (let emoj of emojis) {
	emoj.removeAttribute('title')
}
```

I hardcoded it and tried it by adding it to my Hide Files on Github extension (its `content.js` file)

```js
function init() {
	// Update on fragment update
	const observer = new MutationObserver(update);
	const observeFragment = () => {
		const ajaxFiles = select('include-fragment.file-wrap');
		if (ajaxFiles) {
			observer.observe(ajaxFiles.parentNode, {
				childList: true
			});
		}

		let emojis = document.querySelectorAll('table td[align="center"] a[title] g-emoji')
		for (let emoj of emojis) {
			emoj.removeAttribute('title')
		}
	};

	update();
	observeFragment();
	document.addEventListener('pjax:end', update); // Update on page change
	document.addEventListener('pjax:end', observeFragment);
}
```

the important part is

```js
let emojis = document.querySelectorAll('table td[align="center"] a[title] g-emoji')
for (let emoj of emojis) {
	emoj.removeAttribute('title')
}
```

**Comment by charlike** [comment]
Heya, @kentcdodds, @revelt here's the extension so you can load it:
https://github.com/charlike/all-contributors-patch

**Comment by revelt** [comment]
awesome! fav'd

**Comment by charlike** [comment]
Just not sure for the name and description. Suggestions & PRs welcome, soon will scaffold the repo properly.
