### ISSUE TITLE
New possible contribution type? "Planning" / "API Design" (or something)?

### ISSUE THREAD

**Issue by jmeas** [kentcdodds/all-contributors#60]
Hi there! This project is really cool – nice work @kentcdodds and others! I came here looking to add some contribution boxes to some of my projects, but I didn't feel that any contribution types fit exactly what I was looking for.

Frequently, I find that figuring out the best API for a library can even be more difficult and time-consuming than actually writing the code that implements the API.

Often, I'll work with the developers who will use the library to figure out what an API should be like before running off and coding it. We will have white boarding sessions, phone calls, and basically just spend a long time bike shedding about the best solution. In the end, the coding part can be a small fraction of the total time spent figuring out the problem, and often only a few of the developers involved in all of the conversations will be involved in actually coding the thing.

I'd love to recognize a contribution like this, but there's not currently a contribution type in this repository that seems to line up with this. Do you think an existing type captures this sort of contribution?

If a new type would be warranted, I'm not sure the best name for contributions like this. One idea is "API Design," but that kind of conflicts with "Design." Maybe something like "Planning"? 🤔 

It's also alright if nobody else thinks that a contribution type like this makes sense. Or maybe it's just that this isn't a "contribution" in the sense that this repository is referring. That's completely alright. I just thought I'd open the issue in case anyone else feels the same way.

Thanks for reading!

**Comment by kentcdodds** [comment]
This is great! I was thinking of exactly this today! What about "Ideas & Planning" ? Unfortunately 💡 is already taken, but I like 🤔 as you suggested :smile:

Would you like to [make a pull request](http://makeapullrequest.com)?

**Comment by jmeas** [comment]
Sure thing! Thanks @kentcdodds ✌️

**Comment by sprjr** [comment]
james ur such a 💯.
