### ISSUE TITLE
Platform-specific contribution emoji

### ISSUE THREAD

**Issue by kevinvangelder** [kentcdodds/all-contributors#68]
A lot of times open source projects only support one or a few platforms and a contributor will port or add support for a previously unsupported platform. It would be cool if they could be recognized for that (usually significant) contribution.

**Comment by kentcdodds** [comment]
Agreed 👍 what emoji do you propose?

**Comment by kevinvangelder** [comment]
I was hoping there would be Windows/iOS/Android/MacOS/Linux emoji, but I guess I'm just spoiled by Slack's custom emoji. 😢 Maybe 🚉as a stand-in for "platform"? That's pretty weak, but it's all I've got for the moment. Certainly open to other suggestions.

**Comment by kentcdodds** [comment]
That sounds fine to me! Feel free to [make a pull request](http://makeapullrequest.com) :+1:

**Comment by kevinvangelder** [comment]
I'll give it a bit of time to see if anyone else has better suggestions, but I'm totally up for doing a PR.

**Comment by GantMan** [comment]
:computer: ?

Also, there are colored hearts:
💙  windows?
💚  Android
🖤  iOS
💛  Linux
❤️  Mac
💜  Other

**Comment by kentcdodds** [comment]
I'd rather just have one emoji for the whole concept and 💻 is already taken :)

**Comment by mbbroberg** [comment]
I'm running into similar where I have to recognize the people shepherding that essential part of my projects and it's keeping me from being all in on `all-contributors`.

What about 📦 for packaging/porting?

**Comment by kentcdodds** [comment]
I'm fine with either. The first PR gets to choose the emoji :wink:

**Comment by kevinvangelder** [comment]
I think I like 📦 better than 🚉.

**Comment by mbbroberg** [comment]
Awesome! I didn't want to steal your thunder @kevinvangelder - just happy another internet friend wants to solve the same problem. 😄

**Comment by kentcdodds** [comment]
We'll probably also want a PR on [the cli](https://github.com/jfmengels/all-contributors-cli).

**Comment by mbbroberg** [comment]
Sgtm! Hoping i can get in there but we'll see who can write the codez first.
