### ISSUE TITLE
When to update contributor list

### ISSUE THREAD

**Issue by mpeyper** [kentcdodds/all-contributors#72]
Is there any guidelines on when the list should be updated?

For example, I'd someone raises an issue and a maintainer agrees that it is a bug, I would then deem the user to be a contributor.

Should they be added to the list:

* Immediately?
   * As a PR?
* When the bug is fixed?
* On next commit?
   * Could put some kind of hook in?
* On next release?

I'm committed to including the all-contributors spec in my projects, but I want to ensure I'm doing it right.

**Comment by kentcdodds** [comment]
Hi @mpeyper!

No guidelines. But I generally ask the contributor to add themselves as part of the PR or immediately after it's merged. I don't often keep the list up to date myself and instead leave it up to the contributors to add themselves.

Would you like to add something to the README for a suggestion on how to manage this?

**Comment by mpeyper** [comment]
Thanks @kentcdodds.

My feeling is that it is easy for a contributor to add themselves if they are actively changing the repo (i.e. through a PR), but this is much more difficult if they are contributing to the community without actually committing (e.g. reporting bugs, answering questions on SO, or doing talks/presentations).

Of course, anyone is welcome to submit a PR adding themselves or others to the list, but I think some users may not consider themselves as contributing without a commit, despite what the README declares a contributor to be.  I would hate for these contributors to be missed.

In reality, it will be impossible to catch every case of missed contributor, especially those not on github.  I wonder if the work on #18 and #58 could help in this respect?

> Would you like to add something to the README for a suggestion on how to manage this?

I'm happy to add something once I've figured it out. 😄
