### ISSUE TITLE
Use CONTRIBUTORS.md instead of README.md

### ISSUE THREAD

**Issue by chrissimpkins** [kentcdodds/all-contributors#8]
> People are giving of themselves and their free time to contribute to open source projects in so many ways. It can be a real time sink sometimes and so they should be praised for all their contributions (code or not).

+1 I completely agree.

For projects with a small number of contributors, this will work well under a Contributors heading on a README page.  For larger, very active projects where hundreds (or more) individuals might meet these criteria, this list will be far too large to include on a project README.md file.  I'd recommend that you consider spec'ing a separate CONTRIBUTORS.md page dedicated to these acknowledgments and a link to this page from the project README file.

**Comment by kentcdodds** [comment]
Agreed. Angular or React for example have a TON of contributors in various forms. I'm not even sure this is feasible for a project of that popularity. But I want it to be possible. Do you want to add a disclaimer like this to the spec? Make sure to add yourself to the list of contributors per the spec ;-)

**Comment by chrissimpkins** [comment]
I have some additional thoughts alternating the maintainer and contributor hats (in #9) that expand on this suggestion.  Will close this IR and look forward to your thoughts there.
