### ISSUE TITLE
Internacionalization

### ISSUE THREAD

**Issue by MatheusRV** [kentcdodds/all-contributors#80]
Any ideia how to implement a internacionalization at this doc?

**Comment by kentcdodds** [comment]
I'd be happy to accept a PR to internationalize the docs. Maybe a `docs` directory with markdown files for each locale?

**Comment by shmesa22** [comment]
I can work on Spanish translation

**Comment by ordazgustavo** [comment]
@shmesa22 Are you still working on that?

**Comment by MatheusRV** [comment]
I could translate to pt-br.

**Comment by ordazgustavo** [comment]
I can help with spanish, just wanted to ask before jumping on it

**Comment by MatheusRV** [comment]
@ordazgustavo @shmesa22 Follow https://github.com/kentcdodds/all-contributors/pull/82 to update with spanish translation.

**Comment by MatheusRV** [comment]
Done, now there is a exemple to internacionalization. Tks
